### ISSUE TITLE
Config requires comments with explanations

### ISSUE THREAD

**Issue by GreenDude120** [ccbrown/gggtracker#1]
Hi, I'm working on a few PoE website projects and one of them needs a dev tracker. We were very excited to find your project and instantly tried to set it up, using some volunteer programmers to help.

It has been really hard to fill out the config.inc.php file and still we are getting error with both twitter and forum scans.

I'd really appreciate you take the time to comment for each field and how to find the information or to add me on skype and help us with our project.

We think we found the forum_sessid but it is questionable if our method to get the id was the same as yours. The forum timezone value is also problematic. Also the twitter fields are filled in and yet do not work, suggesting there may be settings to fiddle with from apps.twitter.com directly, as their tokens and secrets still give an error.

Overall we are a bit confused so any help would be very appreciated.

Thanks,
-GreenDude

Skype: GreenDude120
Steam url ID: gd120

**Comment by ccbrown** [comment]
Sure thing. Here's some commenting for you:

https://github.com/ccbrown/gggtracker/commit/fccb9956911f27400faafbb662a74d72513069ad

Hopefully that clears things up. If not, I'll be glad to answer any further questions.

**Comment by ccbrown** [comment]
This'll probably help too:

https://github.com/ccbrown/gggtracker/commit/d511d38e511cff63e079a0ae7a89b161cfc62ffe

**Comment by GreenDude120** [comment]
Okay so we did literally everything. We ran the MySQL file, we have all the fields filled in and the new files uploaded.

The problem we think we are still having is with PHP SessID. How do you get yours? DOes it ever expire? What do you when it expires?

We made a temporary file that redirects the website to pathofexile and then generates a cookie.txt to see the sessid. however we found out today that the id has since changed, pushing us to think that w/e you are doing with the sess id, is completely different, and we need to know how your doing it.


twitter section also crashes and this may be related to needing a certain php package called oauth? We will try to get that installed. For now I don't think twitter is my big concern.

Lastly, do you ever plan on doing a reddit GGG tracker? This is a feature we highly want and we were hopeful you would do this addition to your project. Our team would die for this amazing feature.

Thanks for your help,
-GreenDude

**Comment by ccbrown** [comment]
To get the PHP session id, I log into the Path of Exile website via web browser, using an account made specifically for the tracker. Then, I use the value of the PHPSESSID cookie (In Firefox, I use the [Web Developer extension](https://addons.mozilla.org/en-US/firefox/addon/web-developer/).). I then delete the cookie from the web browser. It's very important that you don't log out after copying the session id. I'm not sure if the session id ever expires under normal circumstances. If it does, it has a very, very long expiration time. When it expires, I just repeat the above process.

You're probably right about requiring that extension for oauth.

No plans for tracking on Reddit, but maybe I'll get bored and do it. And of course, I'm always open to pull requests if someone else wanted to take a shot at it.

**Comment by GreenDude120** [comment]
We got it all working in the end. Thank you so much for the help.

Again we are dieing for a reddit tracker. Although I have contact info of quite a bit of programmers, who help me, i dont know that any of them feel comfortable yet to try and do it and integrate it in your code and all that so, if you feel like doing it, that'd be great.

We will have the code up and running on our new website Nicebuilds.com soon. Thanks again.
