### ISSUE TITLE
Comments in PathofexileBuilds linking to incorrect subreddit

### ISSUE THREAD

**Issue by Dweeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeb** [ccbrown/gggtracker#103]
https://www.reddit.com/r/pathofexile/comments/wjn7so/-/ijiw41a/?context=3 
https://www.reddit.com/r/pathofexile/comments/vztu1e/-/ih0p8ry/?context=3
Two examples, correct links should be 
https://www.reddit.com/r/pathofexilebuilds/comments/wjn7so/-/ijiw41a/?context=3 
https://www.reddit.com/r/pathofexilebuilds/comments/vztu1e/-/ih0p8ry/?context=3

**Comment by ccbrown** [comment]
Thanks! This should be resolved now.
