### ISSUE TITLE
website feed down again 

### ISSUE THREAD

**Issue by DanNeely** [ccbrown/gggtracker#107]
example

https://www.pathofexile.com/forum/view-thread/3320828

**Comment by ccbrown** [comment]
Hmm... Looks fine as far as I can tell:

<img width="1792" alt="Screenshot 2022-11-04 at 9 47 03 PM" src="https://user-images.githubusercontent.com/1731074/200095721-9f3fb8bd-1f25-4432-a03c-b660e84da8da.png">

**Comment by DanNeely** [comment]
Not sure what was going on earlier, looks good for me now too.
