### ISSUE TITLE
gggtracker.com site updates stopped after 12/09

### ISSUE THREAD

**Issue by TwentyFiveEx** [ccbrown/gggtracker#110]
Looks like sync or app that fetches updates has hung. There have been additional GGG posts/updates but last post was 12/09 (it is now 12/11).

![image](https://user-images.githubusercontent.com/109299419/206915204-4491fcd2-663e-4887-bab4-61066632aea1.png)

**Comment by ccbrown** [comment]
Thanks! I've relogged the indexer and we're caught up now.
