### ISSUE TITLE
tracker hung

### ISSUE THREAD

**Issue by TwentyFiveEx** [ccbrown/gggtracker#124]
please restart, ggg expired session tokens again 

i think they might expire sessions several times before a league launch to try to gauge needed launch server capacity, based on how many people actually re-log in.

might be fine to restart the container every 1-2 days during off-peak hours, the week before/after league launch.

thanks!

**Comment by ccbrown** [comment]
Relogged. Thanks! I'll try to keep an eye on it and proactively relog every now and then.
