### ISSUE TITLE
Posts by VASH_GGG not being indexed

### ISSUE THREAD

**Issue by DanNeely** [ccbrown/gggtracker#132]
Initially noticed here:

https://www.pathofexile.com/forum/view-thread/3584143

but it doesn't look like any of their posts are being included:  

https://www.pathofexile.com/account/view-posts/Vash_GGG

**Comment by ccbrown** [comment]
Thanks! I'll get them added later this week when I get a chance.

**Comment by DanNeely** [comment]
I poked through the forums and found a few more GGG accounts to add:

https://www.pathofexile.com/account/view-profile/Cameron_GGG
https://www.pathofexile.com/account/view-profile/Michael_GGG
https://www.pathofexile.com/account/view-profile/Jacob_GGG
https://www.pathofexile.com/account/view-profile/Jenn_GGG
https://www.pathofexile.com/account/view-profile/CoryA_GGG
https://www.pathofexile.com/account/view-profile/Sian_GGG
https://www.pathofexile.com/account/view-profile/Drew_GGG
https://www.pathofexile.com/account/view-profile/Lisa_GGG
https://www.pathofexile.com/account/view-profile/ThomasK_GGG
https://www.pathofexile.com/account/view-profile/Whai_GGG
https://www.pathofexile.com/account/view-profile/Guy_GGG
https://www.pathofexile.com/account/view-profile/Scopey  (shows as GGG on profile)
https://www.pathofexile.com/account/view-profile/Scott_GGG
https://www.pathofexile.com/account/view-profile/Adam_GGG

**Comment by ccbrown** [comment]
Thanks! Added/deployed!
