### ISSUE TITLE
Add more GGG staff accounts

### ISSUE THREAD

**Issue by DanNeely** [ccbrown/gggtracker#134]
I found 3 more currently active GGG accounts:

https://www.pathofexile.com/account/view-profile/Adam_GGG
https://www.pathofexile.com/forum/view-thread/3576083/filter-account-type/staff

https://www.pathofexile.com/account/view-profile/Nichelle_GGG
https://www.pathofexile.com/forum/view-thread/3581957/filter-account-type/staff

https://www.pathofexile.com/account/view-profile/Markus_GGG
https://www.pathofexile.com/forum/view-thread/3586091/filter-account-type/staff

**Comment by ccbrown** [comment]
Thanks! Added!
