### ISSUE TITLE
Forum Indexer appears to be down again

### ISSUE THREAD

**Issue by DanNeely** [ccbrown/gggtracker#135]
I'm not seeing either of these, or anything else from after the 18th:

https://www.pathofexile.com/forum/view-thread/3587332

https://www.pathofexile.com/forum/view-thread/3587517

**Comment by ccbrown** [comment]
Thanks! GGG's addition of account discriminators broke things. Should be all fixed now.

**Comment by DanNeely** [comment]
figures.  They broke almost everything else too.
