### ISSUE TITLE
Forum indexer is currently being blocked by Cloudflare

### ISSUE THREAD

**Issue by ccbrown** [ccbrown/gggtracker#137]
Not sure why this suddenly started. Maybe the site is in DDoS mode or something?

Maybe it'll clear up on its own.

**Comment by ccbrown** [comment]
Issue is still ongoing. I've reached out to GGG for support.

**Comment by DanNeely** [comment]
IF you've only done so via email, posting on the forum might be a good idea.

Email is massively backlogged, and at times their ticketing system was overloaded to the point of not collecting some incoming messages, a forum message could bypass that by being seen and forwarded directly to whatever admin has to deal with cloudflare.

**Comment by DanNeely** [comment]
Never mind, it appears to have been fixed.

**Comment by ccbrown** [comment]
Yep, all good now. Closing this issue, but if/when I hear back I'll update this issue.
