### ISSUE TITLE
Missing poster, Jeff_GGG

### ISSUE THREAD

**Issue by Kyle-Undefined** [ccbrown/gggtracker#17]
Hi,

We use the GGG Tracker RSS in our Xbox Discord and noticed that the tracker doesn't have any posts from Jeff. Looking at the source, I'm assuming it's because he's not in the posters list. 

Normally I'd do a pull request myself, as this looks super easy, but I don't understand anything about Go and would not want to waste anyone's time with a bad pull request, so I figured making an issue would be best.

Jeff's profile is here: https://www.pathofexile.com/account/view-profile/Jeff_GGG

Thank you!

**Comment by ccbrown** [comment]
Thanks! I'll try to take care of this tonight or tomorrow.

**Comment by ccbrown** [comment]
Fixed via ebdeff62ee35b6f0dc6d7503e7523b358c45b70d. Thanks!
