### ISSUE TITLE
Arthur_GGG

### ISSUE THREAD

**Issue by AvocadoCake** [ccbrown/gggtracker#2]
Ever since Dan said "I should point out that many of us aren't on the tracker though, so it's not a totally reliable comparison." - http://www.pathofexile.com/forum/view-thread/1243944/page/2 - I've been thinking it's time to update the list. Arthur_GGG - http://www.pathofexile.com/account/view-profile/Arthur_GGG - isn't on the list.

**Comment by ccbrown** [comment]
Thanks!

On the forums, there's a distinction between "support posts" and "staff posts", and the support posts are generally the things no one wants to see. What I'd like to do (hopefully soon) is add a checkbox or something to filter support posts out. For that reason, accounts like these that just have a handful of support posts haven't really been the biggest priority for me to try to keep up with. I will definitely get it added though.

**Comment by ccbrown** [comment]
Added
