### ISSUE TITLE
Cloudflare SSL handshake failure

### ISSUE THREAD

**Issue by tgavankar** [ccbrown/gggtracker#31]
Visiting https://www.gggtracker.com gives:
Error 525
SSL handshake failed

Note that the site loads fine if you go to https://gggtracker.com directly/explicitly, so there's some DNS misconfiguration somewhere involving the "www" specifically.

**Comment by ccbrown** [comment]
Oops. I totally forgot the tracker ever supported the www subdomain when making some infrastructure changes recently. Thanks for the issue! Should be fixed now.
