### ISSUE TITLE
Tracker now including non-English announcement forums

### ISSUE THREAD

**Issue by viperesque** [ccbrown/gggtracker#36]
Since a forum backend update a few weeks ago, GGGTracker is now showing posts in the announcements forums of the other languages PoE supports, clogging the feed.

**Comment by ccbrown** [comment]
Thanks for the report. Unfortunately the fix isn't gonna be simple. I'll do my best to get to it some time this week though.

**Comment by ccbrown** [comment]
This should be fixed now.

**Comment by viperesque** [comment]
Appreciate it. Seems to have now gone too far the other way though, and is not tracking posts in the English announcements forum.

**Comment by ccbrown** [comment]
Unrelated. The tracker's session token seems to have expired (for the first time ever). That should be fixed too now.
