### ISSUE TITLE
Aggregate from reddit

### ISSUE THREAD

**Issue by Nyfeh** [ccbrown/gggtracker#4]
Wanted to see if it could be possible to also pull from GGG comments on reddit. I'm not familiar with the API for reddit, but I imagine just monitoring the reddit accounts for individuals from GGG would work.

**Comment by ccbrown** [comment]
This has been asked a few times. It's possible, it's relatively easy, and I want the feature as well, but I haven't gotten around to it. I'm open to someone else doing it. Otherwise, I'll get to it some day. I'll keep this issue open until then. Thanks!

**Comment by ccbrown** [comment]
Resolved in the rewrite: f1c8a8d6dd16ef323d1096f71aff45f2f6e7a301. Will be deployed soon.
