### ISSUE TITLE
Tracker not updating with new GGG posts

### ISSUE THREAD

**Issue by viperesque** [ccbrown/gggtracker#48]
Hi,

The tracker hasn't been adding new GGG posts from either the forums or reddit since yesterday.

Sorry for submitting so many issues recently!

**Comment by ZeroCool940711** [comment]
Im seeing the same thing, new posts are not been shown on the gggtracker page, last post I see is an Icefang Brand post from Mark_GGG 3 days ago.

**Comment by ccbrown** [comment]
Thanks for the report! It seems my spot fleet request expired. Should be fixed now.

**Comment by ZeroCool940711** [comment]
@ccbrown It is working correctly now, at least for me.
