### ISSUE TITLE
forum tracker down again

### ISSUE THREAD

**Issue by DanNeely** [ccbrown/gggtracker#58]

**Comment by ccbrown** [comment]
It's still up as far as I can tell. There was a post 25 minutes ago that it got:

<img width="1680" alt="Screen Shot 2020-04-10 at 12 32 01 AM" src="https://user-images.githubusercontent.com/1731074/78962652-c70d4080-7ac2-11ea-80f8-8b22b3d6631d.png">

Have you seen any forum posts that it missed?

Thanks!

**Comment by DanNeely** [comment]
this one was why I raised the issue.  4/9 announcement:

https://www.pathofexile.com/forum/view-thread/2828348

**Comment by DanNeely** [comment]
Two more missing annoucements

https://www.pathofexile.com/forum/view-thread/2835711
https://www.pathofexile.com/forum/view-thread/2835424

**Comment by ccbrown** [comment]
Thanks. I’ll look into this later today.
