### ISSUE TITLE
new GGG reddit account

### ISSUE THREAD

**Issue by DanNeely** [ccbrown/gggtracker#69]
https://www.reddit.com/user/Community_Team

**Comment by DanNeely** [comment]
For something like this in the future would you prefer to get a PR with the change instead of just a notice?  I can add entries in a list easily enough; but don't have a local go install and feel uneasy with the idea of submitting untested changes.

**Comment by ccbrown** [comment]
PRs make things marginally easier for me, but either is fine. In this case someone else submitted a PR anyway. :)
