### ISSUE TITLE
Community_Team not tracked on forum

### ISSUE THREAD

**Issue by SnosMe** [ccbrown/gggtracker#70]

**Comment by DanNeely** [comment]
I assume/hope this issue's sat open because you've been busy with the holidays; but GGG's using this account to post some announcements as well as for general forum support.  With 3.13's announcement in a few days, getting this update deployed would be a major benefit for the community.

**Comment by ccbrown** [comment]
Yep, sorry about that and thanks for the reminder. I'll have it deployed tonight!

**Comment by DanNeely** [comment]
did the deploy fail, or does it not pull old forum posts?  I'm still not seeing anything by the Community_Team forum account.

**Comment by ccbrown** [comment]
Deployed now.
