### ISSUE TITLE
GGGTracker misses Nick_GGG comments (post v2.3.7 release)

### ISSUE THREAD

**Issue by DNekrassov** [ccbrown/gggtracker#98]
As per title - it missed a comment of his: https://www.reddit.com/r/pathofexile/comments/vxm69m/3181d_patch_notes_preview_divine_vessel_soc_fix/ifxanh3/?context=10

**Comment by TwentyFiveEx** [comment]
This PR should fix this:  https://github.com/ccbrown/gggtracker/pull/100
